"""
Generate a complete pull request title, body, and rollback plan.

This is the sixth and final stage of the ZeroDay pipeline. It uses the LLM
to compose a professional, GitHub-flavoured-Markdown pull request description
that summarises the vulnerability, explains the patch, presents test results,
and provides a step-by-step rollback procedure.

Dependencies
------------
lib.llm_client.complete
"""

from __future__ import annotations

from typing import Any

from lib.llm_client import complete


def write_pull_request(
    advisory: dict[str, Any],
    patch: dict[str, Any],
    test_result: dict[str, Any],
) -> dict[str, Any]:
    """
    Draft a pull request title, description, labels, and rollback plan.

    Constructs a rich prompt from the advisory, patch, and test results, then
    asks the LLM to produce a structured JSON response containing all PR
    artefacts. Falls back to plain-text extraction if JSON parsing fails.

    Parameters
    ----------
    advisory : dict[str, Any]
        Parsed advisory from ``parse_cve_advisory``. Must contain ``cve_id``,
        ``description``, ``severity``, ``cvss_score``, and ``references``.
    patch : dict[str, Any]
        Structured patch from ``generate_patch``. Must contain ``patch_type``,
        ``diff``, ``changed_files``, ``patched_version``, and ``explanation``.
    test_result : dict[str, Any]
        Test outcome from ``run_tests``. Must contain ``passed``,
        ``total_tests``, ``passed_tests``, and ``failed_tests``.

    Returns
    -------
    dict[str, Any]
        A pull request artefact dictionary with the following keys:

        title : str
            A concise PR title following the Conventional Commits convention,
            e.g. ``"fix(deps): patch CVE-2024-3772 — pydantic ReDoS (CVSS 7.5)"``.
        description : str
            Full PR body in GitHub-flavoured Markdown. Must include sections
            for: vulnerability summary, patch description, test results table,
            rollback plan, CVE reference with CVSS score, and a ZeroDay footer.
        rollback_plan : str
            Step-by-step rollback instructions in Markdown, extracted from the
            ``description`` for convenient standalone display.
        labels : list[str]
            Suggested GitHub label names for the PR (e.g. ``["security",
            "dependencies", "automated"]``).

    Raises
    ------
    RuntimeError
        If the LLM call fails.
    EnvironmentError
        If ANTHROPIC_API_KEY is not set.

    Dependencies
    ------------
    lib.llm_client.complete : sends the drafting prompt and receives the response.
    """
    # -------------------------------------------------------------------------
    # IMPLEMENTATION NOTES FOR IBM BOB
    #
    # 1. Build a system prompt establishing the LLM persona:
    #    "You are a senior security engineer at a large software company.
    #     You write clear, professional pull request descriptions for automated
    #     vulnerability remediations. You always include rollback instructions
    #     and cite the CVE number."
    #
    # 2. Build a user prompt containing:
    #    a. CVE ID, CVSS score, severity, and description from advisory.
    #    b. Patch type ("version_bump" or "code_fix") and the explanation
    #       from patch["explanation"].
    #    c. The unified diff (patch["diff"]), truncated to 3000 characters if
    #       longer, with a note about truncation.
    #    d. Test results: passed (bool), total_tests, passed_tests, failed_tests.
    #    e. References URLs from advisory["references"] (first 5 only).
    #    f. Instruction to respond with a JSON object:
    #         {
    #           "title": "<string>",
    #           "description": "<markdown string>",
    #           "rollback_plan": "<markdown string>",
    #           "labels": ["<string>", ...]
    #         }
    #
    # 3. Call complete(user_prompt, system=system_prompt).
    #
    # 4. Parse the response as JSON. If parsing fails, treat the entire
    #    response as `description`, derive `title` by taking the first
    #    non-empty line and truncating to 72 characters, set
    #    rollback_plan="" and labels=["security"].
    #
    # 5. Append a standard footer to description:
    #    "\n\n---\n*Generated by [ZeroDay](https://github.com/youraccount/zeroday) "
    #    "using IBM Bob and Claude. CVE details: "
    #    f"https://nvd.nist.gov/vuln/detail/{advisory['cve_id']}*"
    #
    # 6. Ensure `labels` always contains at least "security". Add
    #    "dependencies" if patch_type == "version_bump"; add "automated".
    #
    # 7. Return the structured dict described in the Returns section above.
    # -------------------------------------------------------------------------
    raise NotImplementedError("IBM Bob will implement this in a subsequent session")
